const bookingDetails = [
  {
    bookingId: 1,
    customerName: "Alice Smith",
    contactInfo: {
      email: "alice.smith@example.com",
      phone: "+1 987 654 321",
    },
    roomNumber: "102",
    checkInDate: "20-03-2025",
    checkOutDate: "21-03-2025",
    checkInTime: "02:00 PM",
    checkOutTime: "11:00 AM",
    totalRooms: 1,
    roomTypes: ["Deluxe Rooms"],
    totalGuests: [
      { roomType: "Deluxe Rooms", persons: 2, adult: 1, children: 1 },
    ],
    totalCost: 800,
    bookingStatus: "Confirmed",
    payment: {
      method: "Credit Card",
      amountPaid: 800,
      balanceDue: 0,
    },
    assignedStaff: "Emily Parker",
    specialRequests: ["Extra Towels"],
  },
  {
    bookingId: 2,
    customerName: "Robert Johnson",
    contactInfo: {
      email: "robert.johnson@example.com",
      phone: "+1 234 567 890",
    },
    roomNumber: "103",
    checkInDate: "20-03-2025",
    checkOutDate: "21-03-2025",
    checkInTime: "03:00 PM",
    checkOutTime: "12:00 PM",
    totalRooms: 2,
    roomTypes: ["Deluxe Rooms", "Deluxe Rooms"],
    totalGuests: [
      { roomType: "Deluxe Rooms", persons: 2, adult: 1, children: 1 },
      { roomType: "Deluxe Rooms", persons: 2, adult: 2, children: 1 },
    ],
    totalCost: 1500,
    bookingStatus: "Pending",
    payment: {
      method: "PayPal",
      amountPaid: 1000,
      balanceDue: 500,
    },
    assignedStaff: "David Brown",
    specialRequests: ["Late Check-in"],
  },
  {
    bookingId: 3,
    customerName: "Sophia Brown",
    contactInfo: {
      email: "sophia.brown@example.com",
      phone: "+1 876 543 210",
    },
    roomNumber: "104",
    checkInDate: "20-03-2025",
    checkOutDate: "21-03-2025",
    checkInTime: "01:30 PM",
    checkOutTime: "11:30 AM",
    totalRooms: 1,
    roomTypes: ["Deluxe Room"],
    totalGuests: [
      { roomType: "Deluxe Room", persons: 2, adult: 2, children: 0 },
    ],
    totalCost: 1000,
    bookingStatus: "Confirmed",
    payment: {
      method: "Debit Card",
      amountPaid: 1000,
      balanceDue: 0,
    },
    assignedStaff: "Michael White",
    specialRequests: ["Sea-facing Room"],
  },
  {
    bookingId: 8,
    customerName: "James Wilson",
    contactInfo: {
      email: "james.wilson@example.com",
      phone: "+1 654 321 098",
    },
    roomNumber: "105",
    checkInDate: "20-03-2025",
    checkOutDate: "21-03-2025",
    checkInTime: "02:45 PM",
    checkOutTime: "10:45 AM",
    totalRooms: 2,
    roomTypes: ["Deluxe Rooms", "Deluxe Rooms"],
    totalGuests: [
      { roomType: "Deluxe Rooms", persons: 2, adult: 1, children: 1 },
      { roomType: "Deluxe Rooms", persons: 2, adult: 1, children: 2 },
    ],
    totalCost: 1600,
    bookingStatus: "Cancelled",
    payment: {
      method: "Credit Card",
      amountPaid: 0,
      balanceDue: 1600,
    },
    assignedStaff: "Rachel Green",
    specialRequests: [],
  },
  {
    bookingId: 4,
    customerName: "Emily Davis",
    contactInfo: {
      email: "emily.davis@example.com",
      phone: "+1 789 123 456",
    },
    roomNumber: "106",
    checkInDate: "21-03-2025",
    checkOutDate: "21-03-2025",
    checkInTime: "12:00 PM",
    checkOutTime: "10:00 AM",
    totalRooms: 1,
    roomTypes: ["Deluxe Rooms"],
    totalGuests: [
      { roomType: "Deluxe Rooms", persons: 2, adult: 5, children: 1 },
    ],
    totalCost: 900,
    bookingStatus: "Confirmed",
    payment: {
      method: "Cash",
      amountPaid: 900,
      balanceDue: 0,
    },
    assignedStaff: "Tom Wilson",
    specialRequests: ["Breakfast Included"],
    discount: {
      code: "WELCOME10",
      amount: 100,
    },
  },
  {
    bookingId: 5,
    customerName: "Michael Scott",
    contactInfo: {
      email: "michael.scott@example.com",
      phone: "+1 555 123 456",
    },
    roomNumber: "107",
    checkInDate: "21-03-2025",
    checkOutDate: "21-03-2025",
    checkInTime: "03:15 PM",
    checkOutTime: "12:15 PM",
    totalRooms: 2,
    roomTypes: ["Deluxe Rooms", "Deluxe Rooms"],
    totalGuests: [
      { roomType: "Deluxe Rooms", persons: 2, adult: 1, children: 0 },
      { roomType: "Deluxe Rooms", persons: 2, adult: 2, children: 0 },
    ],
    totalCost: 1400,
    bookingStatus: "Confirmed",
    payment: {
      method: "Bank Transfer",
      amountPaid: 700,
      balanceDue: 700,
    },
    assignedStaff: "Sarah Brown",
    specialRequests: ["King-size Bed"],
    discount: {
      code: "SPRING20",
      amount: 200,
    },
  },
];

export default bookingDetails;
