const RoomDetails = [
  {
    roomType: "Deluxe Rooms",
    maxRoomsAvailable: 15, // Maximum rooms available
    checkIn: "11:00 AM", // Check-in time
    checkOut: "1:00 PM", // Check-out time
    images: [
      "https://res.cloudinary.com/den0iz8zn/image/upload/v1742363284/villaRoom2_flkwqm.jpg",
      "https://res.cloudinary.com/den0iz8zn/image/upload/v1742363268/delRoom10_vnfsfd.jpg",
      "https://res.cloudinary.com/den0iz8zn/image/upload/v1742363160/delRoom1_uenqqh.jpg",
    ],
    capacity: {
      maxPersons: 2,
      maxAdults: 5,
      maxChildren: 2,
    },
    roomInfo: {
      description:
        " Our Spacious Deluxe Rooms offer an elevated experience with generous space, elegant décor, and premium amenities, designed to provide ultimate comfort and relaxation. These rooms feature larger living areas, luxurious furnishings, and stunning views,making them the perfect choice for those seeking extra comfort and sophistication.",
      amenities: [
        "Private bathroom with shower and bathtub",
        "High-speed Wi-Fi",
        "A/C with warmth and cooling options",
        "Free parking",
        "King-size bed",
        "Tea and coffee maker",
      ],
      terms: [
        "Check-in: 1:00 PM | Check-out: 11:00 AM",
        "Alcohol consumption is allowed only in designated areas",
        "Illegal drugs and substances are strictly prohibited",
        "Pets are not allowed",
        "Cancellation policy applies",
      ],
      bed: "This room features a king-size bed with high-quality linens and plush pillows to ensure maximum comfort during your stay.",
    },
    plans: {
      lite: {
        price: {
          twoGuests: { withGst: 4720, withoutGst: 4000 },
          extraAdult: { withGst: 1770, withoutGst: 1500 },
        },
        complimentary: [],
        services: {
          WiFi: true,
          breakfast: false,
          spa: false,
          taxesIncluded: false,
        },
      },
      plus: {
        price: {
          twoGuests: { withGst: 7080, withoutGst: 6000 },
          extraAdult: { withGst: 2124, withoutGst: 1800 },
        },
        complimentary: ["Breakfast"],
        services: {
          WiFi: true,
          breakfast: true,
          spa: false,
          taxesIncluded: false,
        },
        menuDetails: {
          welcomeDrinks: [
            "Watermelon Juice",
            "Lemon Juice",
            "Mint Lemon Juice",
            "Carrot/Beetroot Juice",
          ],
          breakFast: [
            "Idli",
            "Vada",
            "Dosa (Plain, Masala, Onion, Set)",
            "Upma (Rava, Vermicelli)",
            "Kesari Bath",
            "Poha",
            "Poori Sagu",
            "Aloo Paratha (Curd & Pickle)",
            "Tomato Rice",
            "Lemon Rice",
            "Pongal (Karra, Sweet)",
            "Bisi Bele Bath",
            "French Toast",
            "Scrambled Egg",
            "Boiled Egg",
            "Omelette",
            "Sambar",
            "Chutney",
          ],
        },
      },
      max: {
        price: {
          twoGuests: { withGst: 8378, withoutGst: 7100 },
          extraAdult: { withGst: 2596, withoutGst: 2200 },
        },
        complimentary: ["Breakfast", "Snacks", "Dinner"],
        services: {
          WiFi: true,
          breakfast: true,
          spa: false,
          taxesIncluded: false,
        },
        menuDetails: {
          welcomeDrinks: [
            "Watermelon Juice",
            "Lemon Juice",
            "Mint Lemon Juice",
            "Carrot/Beetroot Juice",
          ],
          breakFast: [
            "Idli",
            "Vada",
            "Dosa (Plain, Masala, Onion, Set)",
            "Upma (Rava, Vermicelli)",
            "Kesari Bath",
            "Poha",
            "Poori Sagu",
            "Aloo Paratha (Curd & Pickle)",
            "Tomato Rice",
            "Lemon Rice",
            "Pongal (Karra, Sweet)",
            "Bisi Bele Bath",
            "French Toast",
            "Scrambled Egg",
            "Boiled Egg",
            "Omelette",
            "Sambar",
            "Chutney",
          ],
          dinner: [
            "Veg Starter",
            "Non-Veg Starter",
            "Veg Gravy",
            "Non-Veg Gravy",
            "Rasam",
            "Sambar / Dal",
            "Flavour Rice",
            "White Rice",
            "Chapathi / Pulka",
            "Curd / Papad / Pickle",
            "Salad",
          ],
          snacks: [
            "Ginger Tea",
            "Green Tea",
            "Masala tea",
            "Coffee",
            "Black Tea",
            "Black coffee",
            "Onion rings",
            "Pakoda",
            "Finger chips",
            "Capsiccum Bajji",
            "Mirchi bajji",
          ],
        },
      },
    },
  },
  {
    roomType: "Villa Rooms",
    maxRoomsAvailable: 7, // Maximum rooms available
    checkIn: "11:00 AM", // Check-in time
    checkOut: "1:00 PM", // Check-out time
    images: [
      "https://res.cloudinary.com/den0iz8zn/image/upload/v1742363379/delRoom6_suhg89.webp",
      "https://res.cloudinary.com/den0iz8zn/image/upload/v1742363481/deluxeRoomNew1_r3h85g.webp",
      "https://res.cloudinary.com/den0iz8zn/image/upload/v1742363400/deluxeRoom2_vho3o1.jpg",
    ],
    capacity: {
      maxPersons: 2,
      maxAdults: 1, // Adults (5+ years of age)
      maxChildren: 2, // Children below 5 years
    },
    roomInfo: {
      description:
        "The Individual Villa Rooms provide a private and intimate experience, nestled within beautifully landscaped surroundings.Each villa is designed with its own unique charm, featuring spacious interiors, modern amenities, and private outdoor spaces, ensuring a tranquil retreat for guests who value both luxury and privacy. Our Individual Villa Rooms also  include a charming portico, perfect for relaxing and enjoying the refreshing breeze.",
      amenities: [
        "Private bathroom with shower and bathtub",
        "High-speed Wi-Fi",
        "A/C with warmth and cooling options",
        "Free parking",
        "King-size bed",
        "Tea and coffee maker",
      ],
      terms: [
        "Check-in: 1:00 PM | Check-out: 11:00 AM",
        "Alcohol consumption is allowed only in designated areas",
        "Illegal drugs and substances are strictly prohibited",
        "Pets are not allowed",
        "Cancellation policy applies",
      ],
      bed: "This room features a king-size bed with high-quality linens and plush pillows to ensure maximum comfort during your stay.",
    },
    plans: {
      lite: {
        price: {
          twoGuests: { withGst: 5192, withoutGst: 4400 },
          extraAdult: { withGst: 1770, withoutGst: 1500 },
        },
        complimentary: [],
        services: {
          WiFi: true,
          breakfast: false,
          spa: false,
          taxesIncluded: false,
        },
      },
      plus: {
        price: {
          twoGuests: { withGst: 7552, withoutGst: 6400 },
          extraAdult: { withGst: 2124, withoutGst: 1800 },
        },
        complimentary: ["Breakfast"],
        menuDetails: {
          welcomeDrinks: [
            "Watermelon Juice",
            "Lemon Juice",
            "Mint Lemon Juice",
            "Carrot/Beetroot Juice",
          ],
          breakFast: [
            "Idli",
            "Vada",
            "Dosa (Plain, Masala, Onion, Set)",
            "Upma (Rava, Vermicelli)",
            "Kesari Bath",
            "Poha",
            "Poori Sagu",
            "Aloo Paratha (Curd & Pickle)",
            "Tomato Rice",
            "Lemon Rice",
            "Pongal (Karra, Sweet)",
            "Bisi Bele Bath",
            "French Toast",
            "Scrambled Egg",
            "Boiled Egg",
            "Omelette",
            "Sambar",
            "Chutney",
          ],
        },
        services: {
          WiFi: true,
          breakfast: true,
          spa: false,
          taxesIncluded: false,
        },
      },
      max: {
        price: {
          twoGuests: { withGst: 8850, withoutGst: 7499 },
          extraAdult: { withGst: 2596, withoutGst: 2200 },
        },
        complimentary: ["Breakfast", "Snacks", "Dinner"],
        menuDetails: {
          welcomeDrinks: [
            "Watermelon Juice",
            "Lemon Juice",
            "Mint Lemon Juice",
            "Carrot/Beetroot Juice",
          ],
          breakFast: [
            "Idli",
            "Vada",
            "Dosa (Plain, Masala, Onion, Set)",
            "Upma (Rava, Vermicelli)",
            "Kesari Bath",
            "Poha",
            "Poori Sagu",
            "Aloo Paratha (Curd & Pickle)",
            "Tomato Rice",
            "Lemon Rice",
            "Pongal (Karra, Sweet)",
            "Bisi Bele Bath",
            "French Toast",
            "Scrambled Egg",
            "Boiled Egg",
            "Omelette",
            "Sambar",
            "Chutney",
          ],
          dinner: [
            "Veg Starter",
            "Non-Veg Starter",
            "Veg Gravy",
            "Non-Veg Gravy",
            "Rasam",
            "Sambar / Dal",
            "Flavour Rice",
            "White Rice",
            "Chapathi / Pulka",
            "Curd / Papad / Pickle",
            "Salad",
          ],
          snacks: [
            "Ginger Tea",
            "Green Tea",
            "Masala tea",
            "Coffee",
            "Black Tea",
            "Black coffee",
            "Onion rings",
            "Pakoda",
            "Finger chips",
            "Capsiccum Bajji",
            "Mirchi bajji",
          ],
        },
        services: {
          WiFi: true,
          breakfast: true,
          spa: false,
          taxesIncluded: false,
        },
      },
    },
  },
];

export default RoomDetails;
